version: '3.8'

services:
  vprodb:
    image: youssefcloud24/vprofiledb
    build:
      context: ./db
      dockerfile: dockerfile
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    container_name: vprodb  


  vprocache01:
    image: memcached
    ports:
      - "11211:11211"


  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest


  vproapp:
    image: youssefcloud24/vprofileapp
    build:
      context: ./app
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    volumes: 
      - vproappdata:/usr/local/tomcat/webapps


  vproweb:
    image: youssefcloud24/vprofileweb
    build:
      context: ./web
      dockerfile: dockerfile
    ports:
      - "80:80"
      
volumes:
  vprodbdata: {}
  vproappdata: {}




  



  



