FROM openjdk:11 AS BUILD_IMAGE
RUN apt update && apt install maven -y
RUN git clone https://github.com/nsoc-cloud/deploy-containner-application.git
RUN CD vprofile-project-docker && maven install


FROM tomcat:9.0.91-jre11
RUN rm -rf /usr/local/tomcat/webapps/*
COPY BUILD_IMAGE=vprofile-project-docker/target/vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080

CMD ["catalina.sh" "run"]
